version: '3'

services:
  superset:
    build:
      context: .  # O Dockerfile deve estar no mesmo diretório
      dockerfile: Dockerfile
    container_name: pocker_superset
    env_file:
      - .env  # Carregar variáveis de ambiente do arquivo .env
    ports:
      - "8088:8088"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: pocker_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}  # Usar a variável do .env
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # Usar a variável do .env
      - POSTGRES_DB=${POSTGRES_DB}  # Usar a variável do .env
    volumes:
      - pocker_db:/var/lib/postgresql/data

volumes:
  pocker_db:
